### ISSUE TITLE
Mod installation directory (Mods folder) in Mac is wrong?

### ISSUE THREAD

**Issue by mush00** [javisar/ONI-Modloader-Mods#106]
## Question Description

The mods folder directory for mods installation in Mac is wrong?

## Context

I had tried and error the directory where the mods will work in game, and I found it.

The directory for Mac should be:
/OxygenNotIncluded/OxygenNotIncluded.app/Contents/Resources/Mods

**Comment by javisar** [comment]
Do you mean that the mac folder in the Readme is wrong, right? I've fixed it.
Thanks for pointing it out.
