### ISSUE TITLE
CameraControllerMod doesn't work on new game

### ISSUE THREAD

**Issue by EtiamNullam** [javisar/ONI-Modloader-Mods#11]
As the title says the mod doesn't work when you create new world - you can't zoom out. The functionality is back when you load the save.

**Comment by Killface1980** [comment]
/// <summary>
    /// Needed when a new world is generated. SetMaxOrthographicSize is run once and only then.
    /// </summary>
    [HarmonyPatch(typeof(CameraController), nameof(CameraController.SetMaxOrthographicSize))]
    public static class CameraControllerMod2
    {
        public static void Prefix(CameraController __instance, ref float size)
        {
            size = 100f;
        }
    }

**Comment by Killface1980** [comment]
Oh, just saw the copde in the source. Should be fixed then.

**Comment by javisar** [comment]
Thanks for the tip. Actually that fix doesn't work at least for me. And I cannot find how to fix it :(

**Comment by javisar** [comment]
CameraController removed in favor of @EtiamNullam FreeCamera mod.
