### ISSUE TITLE
missing field exception speedcontrolmod

### ISSUE THREAD

**Issue by cpjet64** [javisar/ONI-Modloader-Mods#110]
## Prerequisites

- [ X] I've made sure the game files are ok before installing injector/mods. 
- [ X] I am running the latest version (master Branch in GitHub)
- [ X] I've checked the logs to see if I can find the problematic mod (test the mods one by one if needed)
- [ X] I checked the documentation and forums and found no answer
- [X ] I checked to make sure that this issue has not already been filed
- [X ] I'm reporting the issue to the correct repository (for multi-repository projects)

## Bug Description

game crashes on new game creation to the blackhole warning
[output_log.txt](https://github.com/javisar/ONI-Modloader-Mods/files/3045862/output_log.txt)
[Mods.zip](https://github.com/javisar/ONI-Modloader-Mods/files/3045863/Mods.zip)
please ignore the error for camera control mod as i have verified the crash happens when the camera control mod is not loaded as well

## Expected Behavior

game doesnt crash xD

## Current Behavior

game crashes on new game creation

## Steps to Reproduce

start game 

## Environment

- OS: Windows 10
- ONI Version: latest
- ONI-Modloader Version: latest

## Output log

Check for error logs in:

- `\OxygenNotIncluded\Mods\Mod_Log.txt`
- `\OxygenNotIncluded\Mods\_Logs`
- Windows: `%USERPROFILE%\AppData\LocalLow\Klei\Oxygen Not Included\output_log.txt`
- Linux: `$home/.config/unity3d/Klei/Oxygen Not Included/Player.log`
- MacOS: `$home/Library/Logs/Unity/Player.log`

## Relevant Code

```Csharp
// TODO(you): code here
```

**Comment by Sijko** [comment]
i'm using the latest beta of ONI, and the speedcontrol mod has no errors for me.

**Comment by cpjet64** [comment]
tnh i dont know. this is a completely fresh install of everything with cloud backup disabled. i ran a verify twice just to make sure it wasnt something else. the mod folder i am currently using is uploaded to this issue as well as the error log.

**Comment by cpjet64** [comment]
just redownloaded and copied the mod over again and now it works like it used to. going to close this issue out.
