### ISSUE TITLE
Publish mods in Steam Workshop

### ISSUE THREAD

**Issue by javisar** [javisar/ONI-Modloader-Mods#116]
@Moonkis @Blindfold @makotech222 @Stzx @dsmiller95

Dear contributors,
Is there any problem if I upload the mods where you have contributed to the Steam Workshop?
Of course, I'll link to the section where the contributors are listed. There is no problem if anyone disagrees.

Regards

**Comment by Blindfold** [comment]
I'm fine with that.

**Comment by dsmiller95** [comment]
That seems like a good idea to me; provided you only upload mods which are not already uploaded since I've already uploaded the TimeLapser mod. Is this only possible now because of the recent updates to ONI?

**Comment by javisar** [comment]
@dsmiller95 oh right, I forgot it. I was going to suggest you to have that mod in you own git. I mean I don't have too much time to maintain more mods and you can have your own mod repo :)

**Comment by dsmiller95** [comment]
@javisar great minds think alike, I broke it away last night :) I was planning on maintaining it myself, so having a separate issue list will be helpful. I'll close the PR then

**Comment by Stzx** [comment]
I have no opinion.
