### ISSUE TITLE
Signs or notes in-game

### ISSUE THREAD

**Issue by fistak** [javisar/ONI-Modloader-Mods#12]
I saw many people desire some way to save some notes about the colony in-game.

A sign tile would be nice, once built it would allow to insert some text in large text area and show it on hover. The problem is that it would need custom sprite of some kind.

The other way is to add additional overlay that would allow to add text over tiles.

This needs to be implemented carefully so nobody will lose the text saved. Of course I prefer saving the data as JSON like I did for temperature overlay and draggable UI.

Tell me what do you think ;)

**Comment by javisar** [comment]
This issue was moved to javisar/ONI-Modloader#26
