### ISSUE TITLE
Airlock not working

### ISSUE THREAD

**Issue by L-a-n-g-o-l-i-e-r-s** [javisar/ONI-Modloader-Mods#14]
Hi there,

Your airlock mod lets both gas and water move freely like a pneumatic airlock. I don't know what I'm supposed to be looking for but it's under the automation tab, right? I tried locking it and I tried wiring it to automation, no change. 

:cry:

**Comment by javisar** [comment]
Yes, in deed, it isn't working at all. It seems like some kind of issue with the Sandbox mode. I'm going to revert the pull merge.

**Comment by javisar** [comment]
I'll close this issue because this mod is not longer mantained.
