### ISSUE TITLE
Mod suggestion: adjustable duplicant O2/CO2 ratio

### ISSUE THREAD

**Issue by keyspace** [javisar/ONI-Modloader-Mods#17]
Actually, I wouldn't mind trying to make it myself.

Any hints on class/entity/property names I'd be looking for?..

[This commented passage in `OxygenBreather` mod](https://github.com/javisar/ONI-Modloader-Mods/blob/e4406aa7387e0523106dac55ee4fcde5cde160ba/Source/Patches/OxygenBreatherMod.cs#L165) seems relevant. But how old is it? Would it still work with Cosmic?..

(Clever way of achieving the mod's goal with `dt=0`, BTW. :+1:)

**Comment by javisar** [comment]
The commented passage is pretty old. Don't use it.
I would suggest to mess with the field OxygenBreather.O2toCO2conversion in a Postfix to the function MinionConfig.CreatePrefab. Or directly with a Transpiler of OxygenBreather.Sim200ms.

**Comment by keyspace** [comment]
Thank you!

I'll close this issue so it doesn't stay hang like a sore. :)
