### ISSUE TITLE
Liquid Stargates

### ISSUE THREAD

**Issue by osa519** [javisar/ONI-Modloader-Mods#22]
When the output stargate reaches pipe block the input continues to draw liquid and they are lost into the void. Is that supposed to happen?

I am using the liquid tank to avoid pipe block now.

**Comment by osa519** [comment]
It actually does go to an infinite storage but not all of the time. i was doing some tests in debug =) Thanks!

**Comment by javisar** [comment]
I fixed some bugs. It works fine for me now. Just to know is that the infinite storage is lost when you save/load the game.
