### ISSUE TITLE
Cloned Master - Missing Unity dependencies?

### ISSUE THREAD

**Issue by altmank** [javisar/ONI-Modloader-Mods#30]
Hey,

I wanted to try my hand at mod coding but ran into a snag here with this repo, it seems the Unity references are not included and it is not part of the solutions Nuget packages.

Help! :)

**Comment by javisar** [comment]
The Unity references are not included. No nuget support.
You have to move them yourself. Step 2 of the following instructions:
https://github.com/javisar/ONI-Modloader#creating-a-mod
Specially:
UnityEngine.dll
UnityEngine.CoreModule.dll
UnityEngine.UI.dll
