### ISSUE TITLE
Freedom of materials

### ISSUE THREAD

**Issue by Gfurst** [javisar/ONI-Modloader-Mods#31]
I heard there was a mod that allowed for more materials to be used, for example steel for pump. If there isn't, would it be possible to make one?

**Comment by javisar** [comment]
There wasn't no materials mod. But it has been pretty easy to do it.
Desire granted! You can try it here:
https://github.com/javisar/ONI-Modloader-Mods/blob/master/Mods/MoreMaterialsMod.dll

Be aware that I almost haven't tested.

**Comment by Gfurst** [comment]
Wow that is pretty great, and fast too thanks.

I actually did find the [other I mentioned](https://github.com/Cairath/ONI-Mods), referred to me by someone on reddit, but by that description yours has much more freedom. I'll test it out.

**Comment by javisar** [comment]
You're welcome.

Yeah, Cairath's mods are awesome.

**Comment by Gfurst** [comment]
Alright managed to test it out. May I ask what exactly does this mod do? Because, while indeed it unlocks most materials for a lot of things, it doesn't unlock it for everything, which resulted in a kind of weird stuff. So I think it may not actually be desirable to just unlock everything, but rather get a closer look on case by case for some interchangeable materials. Let me know what you think.

**Comment by javisar** [comment]
I had to decided which buildings are modified. I didn't see too much sense in changing the ones buildable with plastic.
There isn't a lot of room to choose between materials. The list of possible materials are:
ALL_METALS,RAW_METALS,REFINED_METALS,ALLOYS,ALL_MINERALS,RAW_MINERALS,REFINED_MINERALS,FARMABLE,EXTRUDABLE,PLUMBABLE,PLASTICS,GLASSES,TRANSPARENTS,ANY_BUILDABLE
These are subsets that overlap each other.

I changed to ANY_BUILDABLE. You can see which buildings I changed here:
https://github.com/javisar/ONI-Modloader-Mods/blob/master/Source/MoreMaterialsMod/MoreMaterialsMod.cs

And yeah, probably we have to look on case by case. I'm open to any kind of suggestion.

**Comment by Gfurst** [comment]
Sorry for taking too long to reply, but basically, I think the game needs a overhaul in terms of building materials requirements and how they affect the finished product, (and hopefully the developers already something planned down the map). 

So I don't really think any massive effort would be worth in that regards anyway, something simple I could think of would be making ore and refined metal interchangeable, but besides that I cannot of anything that needs changing atm in any meaningful way.

**Comment by javisar** [comment]
I agree. The thing you comment "making ore and refined metal interchangeable", I think is possible by selecting ANY_BUILDABLE. Not really sure what you mean with interchangeable. I'm gonna close this issue for now. I'll add config files in a not far future.
Thanks @Gfurst
