### ISSUE TITLE
Configurable Liquid and Gas Reservoirs

### ISSUE THREAD

**Issue by javisar** [javisar/ONI-Modloader-Mods#38]

**Comment by rainbowdesign** [comment]
maybe i do this.

**Comment by javisar** [comment]
Thanks for it but you can save your time. I'm almost finished a mod that allows to modify many attributes and config of any building via config files ;)

**Comment by rainbowdesign** [comment]
cool do you add a feature to change elementpropertys too?

**Comment by javisar** [comment]
Maybe, it should be easy once the other mod is finished.

**Comment by javisar** [comment]
It has been included in this new mod:
https://forums.kleientertainment.com/forums/topic/88186-mod04-oni-modloader/?do=findComment&comment=1083834

**Comment by javisar** [comment]
BuildingModifierMod published
