### ISSUE TITLE
Updating old mods

### ISSUE THREAD

**Issue by Adrilahuri** [javisar/ONI-Modloader-Mods#42]
Hi guys,

I was wondering if it was possible to update these 4 old mods from here:
https://github.com/Midnight-Steam/ONI-Modloader

I think @javisar has already worked with Midnight-Steam, and these mods were really good!

-**DefaultDeconstructBuildings**: Sets the default settings to "Buildings" when Deconstruct tool is selected
-**ElectrolyzerIgnorePressure**: Electrolyzer's ignore max pressure
-**MaxAttributeMultiplier**: Changes the attribute multiplier so Duplicants are faster than The Flash(attributes not changed: ImmuneLevelBoost, TemperatureInsulation, SeedHarvestChance)
-**SculptureFlippable**: Makes the sculpture flippable so it can stare at Duplicants from both sides

Thank you for your hard work anyway

**Comment by javisar** [comment]
Re: @Midnight-Steam

**Comment by Midnight-Steam** [comment]
It's been a long time since I've played ONI. Um, I'll take a look into it.
