### ISSUE TITLE
No overheat and no cold damage

### ISSUE THREAD

**Issue by Harmoniumxiv** [javisar/ONI-Modloader-Mods#44]
Hello,

I would like to suggest a mod who will remove the overheat and cold damage.

Thanks !

**Comment by javisar** [comment]
Try this mod
https://github.com/javisar/ONI-Modloader-Mods/blob/NoOverheatMod/Mods/NoOverheatMod.dll
I think it has effect for all buildingss.

**Comment by Harmoniumxiv** [comment]
Thanks i go test

**Comment by Harmoniumxiv** [comment]
The mod work very nice, i have test with an aquatuner and Nothing can happen, but that can still melt, but its already nice.

**Comment by javisar** [comment]
Moved to NoDamageMod

https://github.com/javisar/ONI-Modloader-Mods/commit/da1a2362dd1f927df65d96783f3d33103ac627ef

**Comment by javisar** [comment]
Use the latest version. Upload the log.

**Comment by Sijko** [comment]
i'm also using this . all is ok.

**Comment by Harmoniumxiv** [comment]
[Mod_Log.txt](https://github.com/javisar/ONI-Modloader-Mods/files/2386704/Mod_Log.txt)

Maybe a conflict with another mod

**Comment by javisar** [comment]
You are using and old version of the Modloader, update everything to the latest version, including the game. You should post output_log.txt.
https://github.com/javisar/ONI-Modloader#installation
Step 6

**Comment by Harmoniumxiv** [comment]
I have upload oni modlodader again and replace managed folder and run injector again.
Still crash, what i am doing bad ?
[output_log.txt](https://github.com/javisar/ONI-Modloader-Mods/files/2386844/output_log.txt)

**Comment by javisar** [comment]
You are using and old version of the game, the modloader and using outdated mods... Start clean, remove the game and everything, and reinstall everything.

**Comment by Harmoniumxiv** [comment]
So i have uninstall the game, everything in the folder, and install the game clean from steam. I have download Oni modloader master zip, copy the managed folder into the same game folder, then run injector like usual, then copy the no damage mod. And i still crash, what can i do wrong ?
[output_log.txt](https://github.com/javisar/ONI-Modloader-Mods/files/2386870/output_log.txt)

**Comment by javisar** [comment]
This is the latest version
https://github.com/javisar/ONI-Modloader/tree/master/Managed

**Comment by Harmoniumxiv** [comment]
Yeah i Don't understand why that Don't work, all my other mod work, except this one, i am stuck at the klei logo. I have erased all the folder, fresh install from steam. Then i have downloaded the link you give me, and then copy the managed folder into the managed folder of the game. Then run injector, then i put No damage mod dll on the mods folder + the nodamagestate.json in it, then i launch the game, that it. What i am doing wrong ? First time i have a problem with a mod so i Don't know.
[output_log.txt](https://github.com/javisar/ONI-Modloader-Mods/files/2386986/output_log.txt)

**Comment by javisar** [comment]
Try this
https://support.steampowered.com/kb_article.php?ref=2037-QEUH-3335
And after apply the injector from the link. Post injector output if you can.

**Comment by Harmoniumxiv** [comment]
I have done it, and still the same problem, all other mod work, i give you more screen maybe you can see Something.
![injector 1](https://user-images.githubusercontent.com/43140014/45600829-7bd49e00-ba03-11e8-9307-7371567bf84e.jpg)
![mod 1](https://user-images.githubusercontent.com/43140014/45600831-7d05cb00-ba03-11e8-9fbe-f720cdf08a3a.jpg)
![not working](https://user-images.githubusercontent.com/43140014/45600832-7e36f800-ba03-11e8-8cce-5a811a5c4755.jpg)

**Comment by javisar** [comment]
The json file must be inside its config folder with the same structure than the repo.
/Mods/NoDamage/Config/NoDamageState.json
Please, read the comments.

**Comment by Harmoniumxiv** [comment]
Ok this time i am good, tell me if everything is correct.
![mod 1](https://user-images.githubusercontent.com/43140014/45601128-3797cc80-ba08-11e8-8c00-b46a6b9a3f2f.jpg)

![config 1](https://user-images.githubusercontent.com/43140014/45601132-3ff00780-ba08-11e8-9c2f-d978a331c610.jpg)

But still can't launch the game, the dll is at the good place ?

**Comment by Harmoniumxiv** [comment]
Hello, everything work nice now, i am sorry i didn't know i need the oni common dll, that was the problem… sorry for make you lose your time :(
