### ISSUE TITLE
Sweeper can go through tiles

### ISSUE THREAD

**Issue by Harmoniumxiv** [javisar/ONI-Modloader-Mods#45]
Hello,

i would suggest a mod request who will allow the Sweeper to go through tiles for the gestion of the base that can be awesome.

We have already a nice Sweeper mod created by Rainbow here 👍 

https://github.com/rainbowdesign/OxygenNotIncluded-Mods/blob/master/AutoSweeperMod.dll

If we can add it to this mod that would be nice.

I would suggest add a way to build them without the need of the mechatronic job too.

Thanks a lot.

**Comment by javisar** [comment]
Try this mod

https://github.com/javisar/ONI-Modloader-Mods/blob/AutoSweeperThroughWallsMod/Mods/AutoSweeperThroughWallsMod.dll

**Comment by javisar** [comment]
Continued by @rainbowdesign

**Comment by rainbowdesign** [comment]
Huh? Continued?

**Comment by javisar** [comment]
Well, I meant that you used this piece of code. Isn't correct? I thought it was you.

**Comment by rainbowdesign** [comment]
No i just changed the range of the sweeper

**Comment by javisar** [comment]
Don't you want to maintain the "sweeper through tiles" mod? I have too many mods.

I moved the code here:
https://github.com/javisar/ONI-Modloader-Mods/blob/master/Source/Patches/AutoSweeperThroughWallsMod.cs

**Comment by rainbowdesign** [comment]
I can do that i will merge it then.

**Comment by javisar** [comment]
Great!

**Comment by rainbowdesign** [comment]
The patch has a VERY severe impact on the performance. I cannot fix it hence i cannot maintain the mod like this.
