### ISSUE TITLE
Super duplicant

### ISSUE THREAD

**Issue by Harmoniumxiv** [javisar/ONI-Modloader-Mods#49]
Hello !

I would suggest a mod to give all duplicant 20 to all stats, we have already a save editor, that need to be updated every update, so that would be nice to have something else.

Thanks !

**Comment by javisar** [comment]
MaxAttributeMultiplier
In
https://github.com/Midnight-Steam/ONI-Modloader/

**Comment by Harmoniumxiv** [comment]
After some test this is ok, after some cycle they stop gain level. Thanks for the mods

**Comment by javisar** [comment]
Suggest to him your improvements.
