### ISSUE TITLE
3 new clothings {mod req}

### ISSUE THREAD

**Issue by Sijko** [javisar/ONI-Modloader-Mods#50]
1. Makes the dupe restore HP as in medbed
2. Heat+Cold prot combo
3. Permanent stamina+ so no need to sleep

**Comment by Sijko** [comment]
bonus one - 4. makes 1000 g/s O2 in its cell

**Comment by rainbowdesign** [comment]
You mean you would have to cycle through the dupes and attach the effect manually when he as example wears the HP restore cloth?

**Comment by rainbowdesign** [comment]
I know the special way oni is coded thats why my first idea was to change it with a manual script not with whats onboard the game.
