### ISSUE TITLE
Want some battery?

### ISSUE THREAD

**Issue by codename4748** [javisar/ONI-Modloader-Mods#51]
A mod that allows battery's to be built without a surface..

**Comment by javisar** [comment]
Use BuildingModifierMod with this config:

 "Battery": {
            "BuildLocationRule": "BuildLocationRule.Tile",
            "ContinuouslyCheckFoundation": false,
        },

**Comment by codename4748** [comment]
thanks.btw where are these files.im not a programmer but i can change pretty much anything in don't starve and in few other games.but in oni the files are hidden i guess

**Comment by javisar** [comment]
...\OxygenNotIncluded\Mods\BuildingModifier\Config\

**Comment by codename4748** [comment]
no i meant the game files.not mods.but thanks

**Comment by javisar** [comment]
ONI game files? it depends on your OS.  In windows it use to be

{Drive letter}\Program Files (x86)\Steam\steamapps\common\{Game name}

**Comment by codename4748** [comment]
umm sorry to ask again but thats not working for me . still can't place battery without tile

**Comment by codename4748** [comment]
pls help

**Comment by javisar** [comment]
I just tested it and it works. Use this config in the file \OxygenNotIncluded\Mods\BuildingModifier\Config\BuildingModifierState.json


`{
    "Enabled": true,
    "Debug": false,

    "Modifiers": {

        "Battery": {
            "BuildLocationRule": "BuildLocationRule.Tile",
			"ContinuouslyCheckFoundation": false
        },
		
		"BatteryMedium": {
            "BuildLocationRule": "BuildLocationRule.Tile",
			"ContinuouslyCheckFoundation": false
        },
		
		"BatterySmart": {
            "BuildLocationRule": "BuildLocationRule.Tile",
			"ContinuouslyCheckFoundation": false
        }
	}
}`

**Comment by codename4748** [comment]
oh i was using the old mod files. but now i updated the mod to the latest one and it worked.
