### ISSUE TITLE
A few ideas for mods

### ISSUE THREAD

**Issue by Dirmagnos** [javisar/ONI-Modloader-Mods#52]
Separate mod that would allow configuring random geyser generation on new maps. Allowing or disallowing certain geysers to spawn, and if possible, probabilities of each geyser spawning. And, if possible, limit on how many geysers of each type can spawn per map.

Building modifirt mod was a great addition. 
Suggestion of other buildings to add:
Capacity of all power buildings, how much fuel they can hold.
Battery capacity modification with battery.jouleslostpersecond included to adjust power runoff. For all 3 battery types.
Adjustable storage capacity for: algae terrarium, bottle emptier, farm tiles(i have no idea how to do this, i dug thru code, but it was far beyond me, as it capacity depends of what is planted), fridge. fish feeder, conveyor receptacle, water sieve, ration box, microbe musher, research station and super computer.
Whole capacity tweaking idea is to reduce dupe retardation impact on the game, so that they run less in circles, delivering small amounts of materials. After i set Bottle Emptier to 2000kg, water carrying became far more efficient. Dupes are still retarded, but at least there is less running in this particular case.

If possible, make Neural Vacillation rechargeable over time and require power to recharge.

**Comment by Sijko** [comment]
> After i set Bottle Emptier to 2000kg, water carrying became far more efficient.
what exactly you did ?

**Comment by javisar** [comment]
Added many more configs. Most of the suggested attributes are included.

https://forums.kleientertainment.com/forums/topic/88186-mod04-oni-modloader/?do=findComment&comment=1084471

**Comment by javisar** [comment]
This issue was moved to javisar/ONI-Modloader#31
