### ISSUE TITLE
imp gas col

### ISSUE THREAD

**Issue by Sijko** [javisar/ONI-Modloader-Mods#56]
can you make the color of co2 make more distinguished from low volume o2 and po2 please

**Comment by javisar** [comment]
I think is fine. What do yo suggest, darker co2?

![image](https://user-images.githubusercontent.com/2987197/45594498-f1a51f00-b99b-11e8-9138-68046c7fbf93.png)

**Comment by Sijko** [comment]
yes. or a bit yellowish po2. i don't know how's it with the others but personally me, i can't say is it po2 or co2 without hovering my mouse over it . i use this overlay frequently, so for me it's an issue.

**Comment by javisar** [comment]
Try the latets version of the mod in the repo.
I've added two new parameters FactorValueHSVGases, FactorValueHSVCarbonDioxide.

In your case, try to lower the value of FactorValueHSVCarbonDioxide, by default is 2.0, less than that and the CO2 will be darker.

**Comment by Sijko** [comment]
thank you, mate.
