### ISSUE TITLE
oil refinery no dupe

### ISSUE THREAD

**Issue by Sijko** [javisar/ONI-Modloader-Mods#64]
oil refinery  which works by itself , no need for dupe operating.

**Comment by javisar** [comment]
Please, next time use the template for a mod request:
https://github.com/javisar/ONI-Modloader-Mods/issues/new/choose

**Comment by Sijko** [comment]
i used it. honest

**Comment by javisar** [comment]
This issue was moved to javisar/ONI-Modloader#32
