### ISSUE TITLE
More Cooling for Thermo Aquatuner

### ISSUE THREAD

**Issue by TheInkedOne** [javisar/ONI-Modloader-Mods#67]
Hi, I've been using the mods for some days now and love them, they make this game even better and I was abled to even modify one of the mods to change the wattage used and produced for some machines, but one thing I can't do, no matter what is to modify how much the Thermo Aquatuner cools the liquid. I'm not a coder and understand almost nothing of it and did not found any mods that do that.

So if possible I would love to see a mod that do this, cooling around -30 to -34 ºc with config if possible, or even just the part of the code to do that. 

Sorry for my bad english and thanks in advance.

**Comment by Sijko** [comment]
"LiquidConditioner": {"MassForTemperatureModification": 0,"AirConditioner": {"temperatureDelta":-20.0}},
this goes into BuildingModifierState.json of the BuildingModifier Mod. The -20 is the temp of the cooling.
"MassForTemperatureModification": 0   <--- leave this as it is and use the nodamage mod

**Comment by TheInkedOne** [comment]
Wow. this response was incredible fast! It worked perfectly! Thank you so much for the quick response and help!

**Comment by javisar** [comment]
Very busy these days :(
@Sijko, thank you for the response. 
@TheInkedOne Glad you like the mods :)
I close the issue.
