### ISSUE TITLE
Vent Pressure Mod

### ISSUE THREAD

**Issue by rogeriocamorim** [javisar/ONI-Modloader-Mods#68]
It do not get the value from file. Keep sending gas.

**Comment by javisar** [comment]
Please, fill the issue, with logs.

**Comment by rogeriocamorim** [comment]
VentPressureState.json -> File at \steamapps\common\OxygenNotIncluded\Mods\VentPressure\Config
{
    "Enabled": true,

    "MaximumPressure": {
        "GasVent": 2500,
        "GasVentHighPressure": 2500
    }
}
![image](https://user-images.githubusercontent.com/1370987/46013239-0c654b00-c0a2-11e8-874c-71eac7bccd39.png)

**Comment by javisar** [comment]
2500 are 2500kg
