### ISSUE TITLE
Gas overpressure over config file

### ISSUE THREAD

**Issue by rogeriocamorim** [javisar/ONI-Modloader-Mods#69]
**Prerequisites**
*Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**
	- [ x ] I've made sure the game files are ok before installing injector/mods (https://support.steampowered.com/kb_article.php?ref=2037-QEUH-3335)
	- [ x ] I am running the latest version (Master Branch in github)
	- [ x  ] I've checked the logs to see if I can find the problematic mod (test the mods one by one if needed)
	- [ x ] I checked the documentation and forums and found no answer
	- [ x ] I checked to make sure that this issue has not already been filed
	- [ x ] I'm reporting the issue to the correct repository (for multi-repository projects)
	
**Describe the bug**
I have the mod VentPressureMod.dll installed, also with ONI-Common.dll and the folders needed to work.
At VentPressureState.json (\steamapps\common\OxygenNotIncluded\Mods\VentPressure\Config)
I put this configuration
{
    "Enabled": true,
    "MaximumPressure": {
        "GasVent": 2500,
        "GasVentHighPressure": 2500
    }
}

**Expected behavior**
Gas overpressure not pass 2.5 kg

**Current behavior**
Passing 2.5 kg

**To Reproduce**
Start a game and start sending gas

**Screenshots**
![image](https://user-images.githubusercontent.com/1370987/46013445-b9d85e80-c0a2-11e8-9bd4-bd6088f92c08.png)

**Environment (please complete the following information):**
 - OS: Windows
 - ONI Version RU-285480
 - ONI-Modloader Initializing Modloader v0.4.7

**Comment by javisar** [comment]
Thank you for filling the template. It really helps.
The config is in kg. So it has to reach 2500kg of pressure to stop. You must use 2.5.

**Comment by rogeriocamorim** [comment]
I imagine that, after i write. I suggest put that in documentation because initial config file came as 2000 for normal gas pressure

**Comment by javisar** [comment]
Yeah, the documentation is in the ToDo list.
