### ISSUE TITLE
Fix the Temperature mod of the material color mod

### ISSUE THREAD

**Issue by rainbowdesign** [javisar/ONI-Modloader-Mods#71]
Just keeping track of bug fix and mod requests.

**Comment by javisar** [comment]
Test in branch:
https://github.com/javisar/ONI-Modloader-Mods/tree/TemperatureOverlay

Config file:
/Mods/MaterialColor/Config/TemperatureOverlayState.json

**Comment by javisar** [comment]
Fixed
