### ISSUE TITLE
Buildings attributes UI

### ISSUE THREAD

**Issue by rainbowdesign** [javisar/ONI-Modloader-Mods#73]
It would be nice to add an interface to the aquatuner that sets the target cooling temperature. It should change the power consume and heat output accordingly.

**Comment by javisar** [comment]
For every building in fact.
Too much work for me.

**Comment by Sijko** [comment]
won't it make lags if many coolers?

**Comment by javisar** [comment]
This issue was moved to javisar/ONI-Modloader#34
