### ISSUE TITLE
[Idea] Modportal

### ISSUE THREAD

**Issue by rainbowdesign** [javisar/ONI-Modloader-Mods#74]
I think it would be good to officially register all mods in one place and crosslink them. 

What do you think? Maybe just a new project and a readme and crosslink it?

**Comment by javisar** [comment]
Like this?
https://github.com/javisar/ONI-Modloader/blob/master/README.md#harmony-based-mods

Also there is Nexus...
What do yo mean with "official"?

**Comment by rainbowdesign** [comment]
Something similar.. i would like to change the desription... But there is one other thing: I like to collect modwishes. Or would we do this in your github too?

**Comment by javisar** [comment]
The people seems to use this github for requests to the community, at least I don't feel that the modwishes are for me. Maybe a better place are the forums. You could create a dedicated thread.
I specify at the begining of the readme that the list is open:
`Contribute: There are a list of ideas and requested mods here: https://github.com/javisar/ONI-Modloader-Mods/issues`

Feel free to make pull request, We'll review them. Remember to update from the default branch before do it.

**Comment by rainbowdesign** [comment]
Looks good.
Maybe make a new Label: Modwishes to the Community for wishes you will not take on yourself.
