### ISSUE TITLE
temperature display

### ISSUE THREAD

**Issue by Sijko** [javisar/ONI-Modloader-Mods#75]
## Feature Description
there are some attributes for some things in the game which have arrows showing is it decreasing or increasing, like morale, stress, etc. i would like to someone make a mod if it's possible so every item in the game have such arrows near it's tempature in the last info panel window

## Possible Solution

arrows near tempature in the every item info panel window

**Comment by Sijko** [comment]
![1111asdsaasddddd](https://user-images.githubusercontent.com/32700053/46550909-0dd31680-c8df-11e8-8993-ce1e0807f34f.jpg)

**Comment by javisar** [comment]
This issue was moved to javisar/ONI-Modloader#35
