### ISSUE TITLE
Multiple config files for the building modifier

### ISSUE THREAD

**Issue by rainbowdesign** [javisar/ONI-Modloader-Mods#80]
Would be great to be able to use single config files as module for the building modifier. And also parse subfolders so they could be organized.

**Comment by rainbowdesign** [comment]
I could try myself on it if you dont mind.

**Comment by javisar** [comment]
Go ahead, any contribution is welcome.

**Comment by javisar** [comment]
Implemented in https://github.com/javisar/ONI-Modloader-Mods/pull/100
Still needs work.

**Comment by rainbowdesign** [comment]
Whats the problem with it?
