### ISSUE TITLE
Elements/Recipes/Animal Modifier

### ISSUE THREAD

**Issue by rainbowdesign** [javisar/ONI-Modloader-Mods#81]
It would be nice to have some more settings to change with the modifier:
Building recipes, animals and diet aswell as elements. I have seen cairath did boast with having made a mod for elements in 25 minutes... But i would like it more to have it all at one place instead of installing a bunch of dlls.

**Comment by javisar** [comment]
I prefer to keep the mods simple and separated.

Why don't you ask to Cairath to publish the element editor?

**Comment by rainbowdesign** [comment]
i think it will be published anyways. If i wanted to change the hotter than lava mod to be a script for the building modifier it feels annoying to add to download 3 different extra files.

**Comment by javisar** [comment]
Make a mod pack

**Comment by rainbowdesign** [comment]
What do you mean "mod pack"? One idea is that the player has the updated building modifier. Assuming i zip the three files in i would need to also update it.

**Comment by javisar** [comment]
With "mod pack" I mean a zip yes. You'll have to update it if there are changes.

**Comment by rainbowdesign** [comment]
For me there are always two reasons to merge mods: 
One is merged mods need less maintance. 
Two merged mods have less hassle to download and less clutter in the modfolder but also less conflicting and more streamlined.

Assuming you would ever have single config files to change buildings you have something like a basic configuration engine. It would be a small thing to expose more of the game since you have the engine already. Adding animals would be an extension to the mod capability.

Ultimately what i propose is to extend the scope of the mod from a building Modifier to a General modifier exposing "all you need" to little config snippets.

Now what reason not to merge it:
Most common: There are drawbacks when installing a mod like someone would not want the new features.

Assuming you just provide an infrastructure with the dlls and the real change is in the mod files the mod does not do anything without the config.

**Comment by javisar** [comment]
This issue was moved to javisar/ONI-Modloader#36
