### ISSUE TITLE
Pounding Sand - SuperMinerMod

### ISSUE THREAD

**Issue by Nuclearmayhem** [javisar/ONI-Modloader-Mods#82]
Seems that Klei has introduced a new system on stacking and I think it's messed with this mod.

Whenever the dupes dig anything that falls like sand or snow it just keeps reforming and they dig all day until I stop them or break time kicks in.  Was working fine til the last couple patches.  In many cases it looks like they're gaining progress until they stop.

![20181018121801_1](https://user-images.githubusercontent.com/30328895/47169042-861edc00-d2d0-11e8-9869-f9ceedaf7785.jpg)

**Comment by Sijko** [comment]
you know, smart guys dig only the bottom tile of such elements. You know, like in Terraria.

**Comment by Nuclearmayhem** [comment]
While the screen shot shows multiple people, it also does it when digging just the bottom tile with one dupe.  The only way I can clear a pile of sand/show is if I start from the top and dig down.  Here's my one digger pounding sand :)

![20181018130313_1](https://user-images.githubusercontent.com/30328895/47171148-f11ee180-d2d5-11e8-83b6-a2ed0f6a738b.jpg)

**Comment by Nuclearmayhem** [comment]
Well, don't I feel foolish.  You can delete this.  I tried reinstalling ONI, the mod program and just the superminer mod and it works fine. 

I think at some point one of the updates replaced my 0harmony.dll file on me which is what may have been what caused the weird digging.

**Comment by javisar** [comment]
This update Klei has added Harmony in the game itself. Easy mode :D

https://forums.kleientertainment.com/forums/topic/88186-mod05-oni-modloader/?do=findComment&comment=1098474
