### ISSUE TITLE
Issue with MaterialColor and Cairath's MosaicTile mod

### ISSUE THREAD

**Issue by funnysunnybunny** [javisar/ONI-Modloader-Mods#88]
Blackhole eating game after construction finished, is there any easy quickfix to make it compatible?

**Comment by javisar** [comment]
Attach the log file.

**Comment by funnysunnybunny** [comment]
[output_log.txt](https://github.com/javisar/ONI-Modloader-Mods/files/2521782/output_log.txt)
https://pastebin.com/pVPqQBFw

Oh I thought I replied already but it seems upload failed/comment didn't work and I didn't notice, sorry for forgetting log file and thanks!

**Comment by javisar** [comment]
No problem.
Wow, how many mods are you using! lol. ONI isn't skyrim :D
I'm not sure why it crash but I've made a little fix and it seems to work. Check the latest version of MaterialColor and let me know how it goes.

**Comment by funnysunnybunny** [comment]
Hey thanks a lot! Seems to be working fine.
Hehe, Skyrim a game I get stuck with loot and similar tools merging, if a few days all the other oni packages were updated I'd have used half a dozen more! Sometimes I even hand test every single one of yours if they run on the experimental, I have a problem! ^^

**Comment by javisar** [comment]
Good! I'll close the issue. Thanks for the testing.
