### ISSUE TITLE
Stargates stops after longer time without saving / loading

### ISSUE THREAD

**Issue by rainbowdesign** [javisar/ONI-Modloader-Mods#89]
Stargates seem to stop working after a time.

Sometimes its only new stargates that stop working. Liquid and gas are seperated like this case liquid stargates stopped working while gas still work (but stopped later).
Sometimes all stargates seems to stop.
It seems to happen when oni runs long time in the background and after 100+ turns without saving.
Reload might fix stargates but does not always.
On Reload and restart: Gas and liquid goes into the stargate but does not come out again. In all they dont feel very reliable.

**Comment by RedPia** [comment]
I have the same problem as rainbowdesign, but i cant even get it starting anymore. the Gas-stargate works perfect for me so far, but the liquid one is dead.

anyways, nice work! keep it up :)

**Comment by javisar** [comment]
@rainbowdesign, could you try the latest version? I've merged the fix from @Blindfold, maybe this fix works better.

https://github.com/javisar/ONI-Modloader-Mods/blob/master/Mods/FluidWarpMod.dll

**Comment by javisar** [comment]
https://github.com/javisar/ONI-Modloader-Mods/pull/105
