### ISSUE TITLE
AlternanteOrdersMod breaks the cycles

### ISSUE THREAD

**Issue by javisar** [javisar/ONI-Modloader-Mods#9]
Cooking station breaks the cycles if any ingredient is missing

**Comment by fistak** [comment]
What do you suggest? Keep cycling through the queue until one with sufficient ingredients is found?

**Comment by javisar** [comment]
I'm not sure. I have to test it to see exactly what's the problem.

**Comment by Blindfold** [comment]
I guess the upcoming update will make this mod obsolete.
From the prerelease notes:

> Major revision to the recipe screen for fabrication buildings like the Cook Station and Refinery. Currently they all use the same UI. Now, the UI allows setting a number or infinite amount of any recipe, and recipes without ingredients will be skipped automatically. This UI will be further developed during the testing period.

**Comment by javisar** [comment]
Correct, I saw it,, and I quite happy with that.
Also DisplayDraggedBoxSize becomes obsolete.

**Comment by Blindfold** [comment]
Does it means that devs are monitoring what mod-developers do? That would be great! :)

**Comment by javisar** [comment]
I close the issue since the mod is deprecated with the inclusion in vanilla game.
