### ISSUE TITLE
Question/Issue about BuildingModifier config

### ISSUE THREAD

**Issue by Nuclearmayhem** [javisar/ONI-Modloader-Mods#92]
I'm trying to adjust some of the buildings so that they will build with all metal options.  I'm using the BuildingModifierState.json file. 

I'm using the TUNING.MATERIALS.ALL_METALS listed in the morematerials file but when I load the game the only metal options I get are the raw metals and some of the alloy's like steel and above,  none of the refined metals like gold and tungsten are showing.

I don't like using the all materials option because I end up building things like sandstone pumps.

Am I doing something wrong?

**Comment by javisar** [comment]
Nothing wrong.
Just that TUNING.MATERIALS.ALL_METALS only includes the elements categorized by ONI as "Metal" and they don't include some of the refined metals into that category.

**Comment by Nuclearmayhem** [comment]
Damn, alright I'll just have to live with using all buildable.  Hopefully ONI will update some of the refined materials as metals as you'd think gold and tungsten would be labeled as such.   Thanks  :)
